server:
  port: 8090

spring:
  application:
    name: testing-entity
  datasource:
    username: postgres
    password: xBMv4sn9
    url: jdbc:postgresql://localhost:5432/testing
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      format_sql: true
#  sql:
#    init:
#      schema-locations: testing

logging:
  level:
    root: INFO
